FROM python:3.11

WORKDIR /app

# 1) install deps
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 2) copy code
COPY . .

# 3) expose & run
EXPOSE 8080
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
